#!/bin/sh

# script to put parse.c back togther
# and (silently) recover mawk.doc
#
#

if cat parse.c.01 parse.c.02 parse.c.03 > parse.c
   then
   rm parse.c.01 parse.c.02 parse.c.03 
   else
   echo cannot create parse.c 1>&2
   error=1
fi

if cat man/doc.uue.01 man/doc.uue.02 | ( cd man ; uudecode > mawk.doc )
   then
   rm man/doc.uue.01 man/doc.uue.02
   else
   echo error creating mawk.doc 1>&2
   exit 1
fi

exit $error


